"""
fig6_six_scheme_compare.py
====================================================================
Produces the six-scheme NOMA comparison (results/figures/fig6a_six_schemes.png):

  1. Proposed scheme            (RIS + ML optimisation)     -- MAML policy
  2. Equal power alloc          + random RIS phases
  3. Random power alloc         + random RIS phases
  4. Equal power alloc          + fixed  RIS phases
  5. Random power alloc         + fixed  RIS phases
  6. NOMA + No-RIS

All six schemes are evaluated on the SAME held-out test channels
(fig6_ris_test_channels.npz for schemes 1-5, fig6_noris_test_channels.npz
for scheme 6, both produced by gen_fig6_channels.py), so the comparison
is apples-to-apples.

Metric plotted / tabulated: the weighted objective
    R_DL_sum = w_c*(R_n + R_f) + w_s*R_s ,  (w_c, w_s) = (0.7, 0.3)
used throughout compare_noma_fair.py.

Physics for schemes 1-5 (RIS branch, M=4, N=8) reuses the exact
closed-form beamformers from train_noma_fair_maml.physics_step:
  - w_c (cluster/common beam): fixed fair-weighted beam
    0.7*h_f + 0.3*h_n, identical in all five RIS schemes.
  - w_T (sensing beam): soft-null top eigenvector of
    G_T^H G_T - 0.5 * H_u H_u^H, identical in all five RIS schemes.
Scheme 1 (Proposed) additionally runs the trained AlphaNet
(policy_noma_fair_best.pt, the same checkpoint used for every other
NOMA-RIS number in this repo) through its K-step inner-loop RIS-phase
adaptation (inner_optimize(), identical procedure to training/eval).
Schemes 2-5 use random-draw power/phase instead of the learned policy.
Physics for scheme 6 (no-RIS, M=4) reuses train_noma_fair_noris.py's
noris_gains() with the trained policy_noris_best.pt power-split network.

Random phase  = fresh i.i.d. Uniform(0, 2*pi) phase per channel sample
                (matches the "baseline" construction already used in
                compare_noma_fair.py / train_noma_fair_maml.baseline_eval).
Fixed  phase  = a single phase profile (all phi_i = 0, i.e. Theta = I,
                the RIS reflects with no reconfiguration) applied to every
                channel sample -- the standard "non-reconfigured RIS"
                baseline in the RIS literature.
Equal  power  = (a_n, a_f, a_T) = (1/3, 1/3, 1/3) for every sample.
Random power  = a fresh softmax(Normal(0,1)) draw per sample (same
                construction as compare_noma_fair.build_randPhi_randAlpha_fn).

Outputs (written to results/csv/):
  fig6_six_scheme_summary.csv   (mean R_n, R_f, R_s, R_DL_sum, qos per scheme)
  fig6_six_scheme_percurve.csv  (per-channel R_DL_sum for all 6 schemes, for
                                  CDF plotting in MATLAB or Python)
"""
import sys
from pathlib import Path

import numpy as np
import torch

# ------------------------------------------------------------------
# This script lives in src/, as a sibling of the other trainers/
# evaluators it imports from, and of models/ and results/.
# ------------------------------------------------------------------
HERE = Path(__file__).resolve().parent          # .../src
REPO_ROOT = HERE.parent                         # repo root
MODELS = REPO_ROOT / "models"
RESULTS_CSV = REPO_ROOT / "results" / "csv"
sys.path.insert(0, str(HERE))

from train_noma_fair_maml import (
    AlphaNet, physics_step, rates_from_gains as rates_from_gains_fixedbeam,
    make_features as make_features_fixedbeam, lagrangian_loss as lagrangian_loss_fixedbeam,
    inner_optimize,
)

DEVICE = torch.device("cpu")
W_C, W_S = 0.7, 0.3   # weighted objective, R_DL = w_c*(R_n+R_f) + w_s*R_s


# ------------------------------------------------------------------
# Load held-out test channels generated by gen_fig6_channels.py
# ------------------------------------------------------------------
def load_ris_channels():
    d = np.load(HERE / "fig6_ris_test_channels.npz")
    H_BR = torch.from_numpy(d["H_BR"])
    h_RDn = torch.from_numpy(d["h_RDn"])
    h_RDf = torch.from_numpy(d["h_RDf"])
    h_RT = torch.from_numpy(d["h_RT"])
    h_TR = torch.from_numpy(d["h_TR"])
    return H_BR, h_RDn, h_RDf, h_RT, h_TR, int(d["N"]), int(d["M"])


def load_noris_channels():
    d = np.load(HERE / "fig6_noris_test_channels.npz")
    h_BDn = torch.from_numpy(d["h_BDn"])
    h_BDf = torch.from_numpy(d["h_BDf"])
    h_BT = torch.from_numpy(d["h_BT"])
    return h_BDn, h_BDf, h_BT, int(d["M"])


# ------------------------------------------------------------------
# Scheme 1: Proposed (RIS + ML optimisation) -- same MAML policy and
# inner-loop procedure used for every other NOMA-RIS number in this
# repo (policy_noma_fair_best.pt).
# ------------------------------------------------------------------
class _InnerArgs:
    """Mimics the argparse.Namespace that inner_optimize() expects,
    using the exact hyper-parameters stored in the checkpoint."""
    def __init__(self, d):
        defaults = dict(w_c=0.7, w_s=0.3, inner_steps=10, inner_lr=0.1,
                        gamma_theta=0.3, lam_c=2.0, lam_s=50.0,
                        lam_n=15.0, lam_f=20.0, R_th_n=1.0, R_th_f=1.0)
        for k, v in defaults.items():
            setattr(self, k, v)
        for k, v in d.items():
            setattr(self, k, v)


def run_proposed(H_BR, h_RDn, h_RDf, h_RT, h_TR, cfg, ckpt_path, batch=256):
    ck = torch.load(ckpt_path, map_location=DEVICE, weights_only=False)
    net = AlphaNet(in_dim=9, hidden=ck["args"].get("hidden", 256)).to(DEVICE)
    net.load_state_dict(ck["state_dict"]); net.eval()
    ia = _InnerArgs(ck["args"])

    n = H_BR.shape[0]
    Rn_all, Rf_all, Rs_all = [], [], []
    for i in range(0, n, batch):
        sl = slice(i, min(i + batch, n))
        batch_t = (H_BR[sl], h_RDn[sl], h_RDf[sl], h_RT[sl], h_TR[sl])
        with torch.enable_grad():
            _, _, R_n, R_f, R_s, _, _ = inner_optimize(
                net, batch_t, cfg, ia, create_meta_graph=False)
        Rn_all.append(R_n.detach().numpy())
        Rf_all.append(R_f.detach().numpy())
        Rs_all.append(R_s.detach().numpy())

    return np.concatenate(Rn_all), np.concatenate(Rf_all), np.concatenate(Rs_all)


# ------------------------------------------------------------------
# Schemes 2-5: fixed-beam physics + (equal|random) power x (random|fixed) phase
# ------------------------------------------------------------------
@torch.no_grad()
def run_fixed_beam_scheme(H_BR, h_RDn, h_RDf, h_RT, h_TR, cfg,
                           power_mode, phase_mode, seed, batch=256):
    n = H_BR.shape[0]
    N = cfg["N"]
    Rn_all, Rf_all, Rs_all = [], [], []
    g = torch.Generator().manual_seed(seed)

    # "fixed" RIS phase profile: single non-reconfigured phase vector
    # (all phi_i = 0, i.e. Theta = I -- the RIS passes signals through
    # with no phase reconfiguration), applied identically to every sample.
    fixed_phi_single = torch.zeros(N)

    for i in range(0, n, batch):
        sl = slice(i, min(i + batch, n))
        batch_t = (H_BR[sl], h_RDn[sl], h_RDf[sl], h_RT[sl], h_TR[sl])
        B = batch_t[0].shape[0]

        if phase_mode == "random":
            phi = 2 * np.pi * torch.rand(B, N, generator=g)
        elif phase_mode == "fixed":
            phi = fixed_phi_single.unsqueeze(0).expand(B, N)
        else:
            raise ValueError(phase_mode)

        if power_mode == "equal":
            alpha = torch.tensor([1 / 3, 1 / 3, 1 / 3]).expand(B, 3)
        elif power_mode == "random":
            alpha = torch.softmax(torch.randn(B, 3, generator=g), dim=-1)
        else:
            raise ValueError(power_mode)

        gains = physics_step(phi, *batch_t, cfg["beta_T"])
        R_n, R_f, R_s = rates_from_gains_fixedbeam(gains, alpha, cfg["P_tot"], cfg["sigma2"])
        Rn_all.append(R_n.numpy()); Rf_all.append(R_f.numpy()); Rs_all.append(R_s.numpy())

    return np.concatenate(Rn_all), np.concatenate(Rf_all), np.concatenate(Rs_all)


# ------------------------------------------------------------------
# Scheme 6: NOMA + No-RIS (trained policy on direct-link channels)
# ------------------------------------------------------------------
def run_noris(h_BDn, h_BDf, h_BT, cfg, ckpt_path, batch=256):
    from train_noma_fair_noris import (
        noris_gains, rates_from_gains as rates_from_gains_noris,
        make_features as make_features_noris, AlphaNet,
    )
    ck = torch.load(ckpt_path, map_location=DEVICE, weights_only=False)
    net = AlphaNet(in_dim=9, hidden=ck["args"].get("hidden", 256)).to(DEVICE)
    net.load_state_dict(ck["state_dict"]); net.eval()

    n = h_BDn.shape[0]
    Rn_all, Rf_all, Rs_all = [], [], []
    with torch.no_grad():
        for i in range(0, n, batch):
            sl = slice(i, min(i + batch, n))
            h_n, h_f, h_bt = h_BDn[sl], h_BDf[sl], h_BT[sl]
            gains = noris_gains(h_n, h_f, h_bt, cfg["beta_T"])
            feats = make_features_noris(gains, cfg["R_th_c"], cfg["R_th_s"], cfg["P_tot"], cfg["sigma2"])
            alpha = net(feats)
            R_n, R_f, R_s = rates_from_gains_noris(gains, alpha, cfg["P_tot"], cfg["sigma2"])
            Rn_all.append(R_n.numpy()); Rf_all.append(R_f.numpy()); Rs_all.append(R_s.numpy())

    return np.concatenate(Rn_all), np.concatenate(Rf_all), np.concatenate(Rs_all)


# ------------------------------------------------------------------
# Main
# ------------------------------------------------------------------
def main():
    H_BR, h_RDn, h_RDf, h_RT, h_TR, N, M = load_ris_channels()
    h_BDn, h_BDf, h_BT, M_noris = load_noris_channels()

    ckpt_proposed = MODELS / "noma-fair" / "policy_noma_fair_best.pt"
    ckpt_noris = MODELS / "no-ris" / "policy_noris_best.pt"

    c_prop = torch.load(ckpt_proposed, map_location=DEVICE, weights_only=False)["cfg"]
    c_nor = torch.load(ckpt_noris, map_location=DEVICE, weights_only=False)["cfg"]

    cfg_ris = dict(N=N, M=M, P_tot=c_prop["P_tot"], sigma2=c_prop["sigma2"],
                   beta_T=c_prop["beta_T"], R_th_c=c_prop["R_th_c"], R_th_s=c_prop["R_th_s"])
    cfg_noris = dict(M=M_noris, P_tot=c_nor["P_tot"], sigma2=c_nor["sigma2"],
                      beta_T=c_nor["beta_T"], R_th_c=c_nor["R_th_c"], R_th_s=c_nor["R_th_s"])

    print(f"RIS cfg   : N={cfg_ris['N']} M={cfg_ris['M']} P_tot={cfg_ris['P_tot']:.3e} "
          f"beta_T={cfg_ris['beta_T']:.1f} R_th_c={cfg_ris['R_th_c']} R_th_s={cfg_ris['R_th_s']}")
    print(f"NoRIS cfg : M={cfg_noris['M']} P_tot={cfg_noris['P_tot']:.3e} "
          f"beta_T={cfg_noris['beta_T']:.1f} R_th_c={cfg_noris['R_th_c']} R_th_s={cfg_noris['R_th_s']}")

    schemes = {}

    print("\n[1/6] Proposed scheme (RIS + ML optimization) ...")
    schemes["Proposed (RIS+ML optimization)"] = run_proposed(
        H_BR, h_RDn, h_RDf, h_RT, h_TR, cfg_ris, ckpt_proposed)

    print("[2/6] Equal power + random RIS phases ...")
    schemes["Equal power + random RIS phases"] = run_fixed_beam_scheme(
        H_BR, h_RDn, h_RDf, h_RT, h_TR, cfg_ris, "equal", "random", seed=1)

    print("[3/6] Random power + random RIS phases ...")
    schemes["Random power + random RIS phases"] = run_fixed_beam_scheme(
        H_BR, h_RDn, h_RDf, h_RT, h_TR, cfg_ris, "random", "random", seed=2)

    print("[4/6] Equal power + fixed RIS phases ...")
    schemes["Equal power + fixed RIS phases"] = run_fixed_beam_scheme(
        H_BR, h_RDn, h_RDf, h_RT, h_TR, cfg_ris, "equal", "fixed", seed=3)

    print("[5/6] Random power + fixed RIS phases ...")
    schemes["Random power + fixed RIS phases"] = run_fixed_beam_scheme(
        H_BR, h_RDn, h_RDf, h_RT, h_TR, cfg_ris, "random", "fixed", seed=4)

    print("[6/6] NOMA + No-RIS ...")
    schemes["NOMA + No-RIS"] = run_noris(h_BDn, h_BDf, h_BT, cfg_noris, ckpt_noris)

    # -------------------- aggregate + save --------------------
    summary_rows = []
    percurve = {}
    for name, (R_n, R_f, R_s) in schemes.items():
        Rsum = W_C * (R_n + R_f) + W_S * R_s
        qc = (R_n + R_f) < cfg_ris["R_th_c"]
        qs = R_s < cfg_ris["R_th_s"]
        qany = qc | qs
        summary_rows.append(dict(
            scheme=name, R_n=R_n.mean(), R_f=R_f.mean(), R_s=R_s.mean(),
            R_DL_sum=Rsum.mean(), qos_viol_any=qany.mean()))
        percurve[name] = Rsum
        print(f"  {name:<40s}  R_DL_sum={Rsum.mean():7.3f}  "
              f"R_n={R_n.mean():6.3f}  R_f={R_f.mean():6.3f}  R_s={R_s.mean():6.3f}")

    import csv
    RESULTS_CSV.mkdir(parents=True, exist_ok=True)
    with open(RESULTS_CSV / "fig6_six_scheme_summary.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["scheme", "R_n", "R_f", "R_s", "R_DL_sum", "qos_viol_any"])
        w.writeheader()
        for r in summary_rows:
            w.writerow(r)

    # per-curve CSV (ragged -> pad with NaN to common length for a simple CSV)
    maxlen = max(len(v) for v in percurve.values())
    names = list(percurve.keys())
    with open(RESULTS_CSV / "fig6_six_scheme_percurve.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(names)
        for i in range(maxlen):
            row = [percurve[nm][i] if i < len(percurve[nm]) else "" for nm in names]
            w.writerow(row)

    print(f"\nSaved -> {RESULTS_CSV/'fig6_six_scheme_summary.csv'}")
    print(f"Saved -> {RESULTS_CSV/'fig6_six_scheme_percurve.csv'}")


if __name__ == "__main__":
    main()
